"""Phonetic syllable tables (from vere/pkg/noun/jets/c/po.c)."""
PREFIXES = [
    "doz", "mar", "bin", "wan", "sam", "lit", "sig", "hid",  # 0-7
    "fid", "lis", "sog", "dir", "wac", "sab", "wis", "sib",  # 8-15
    "rig", "sol", "dop", "mod", "fog", "lid", "hop", "dar",  # 16-23
    "dor", "lor", "hod", "fol", "rin", "tog", "sil", "mir",  # 24-31
    "hol", "pas", "lac", "rov", "liv", "dal", "sat", "lib",  # 32-39
    "tab", "han", "tic", "pid", "tor", "bol", "fos", "dot",  # 40-47
    "los", "dil", "for", "pil", "ram", "tir", "win", "tad",  # 48-55
    "bic", "dif", "roc", "wid", "bis", "das", "mid", "lop",  # 56-63
    "ril", "nar", "dap", "mol", "san", "loc", "nov", "sit",  # 64-71
    "nid", "tip", "sic", "rop", "wit", "nat", "pan", "min",  # 72-79
    "rit", "pod", "mot", "tam", "tol", "sav", "pos", "nap",  # 80-87
    "nop", "som", "fin", "fon", "ban", "mor", "wor", "sip",  # 88-95
    "ron", "nor", "bot", "wic", "soc", "wat", "dol", "mag",  # 96-103
    "pic", "dav", "bid", "bal", "tim", "tas", "mal", "lig",  # 104-111
    "siv", "tag", "pad", "sal", "div", "dac", "tan", "sid",  # 112-119
    "fab", "tar", "mon", "ran", "nis", "wol", "mis", "pal",  # 120-127
    "las", "dis", "map", "rab", "tob", "rol", "lat", "lon",  # 128-135
    "nod", "nav", "fig", "nom", "nib", "pag", "sop", "ral",  # 136-143
    "bil", "had", "doc", "rid", "moc", "pac", "rav", "rip",  # 144-151
    "fal", "tod", "til", "tin", "hap", "mic", "fan", "pat",  # 152-159
    "tac", "lab", "mog", "sim", "son", "pin", "lom", "ric",  # 160-167
    "tap", "fir", "has", "bos", "bat", "poc", "hac", "tid",  # 168-175
    "hav", "sap", "lin", "dib", "hos", "dab", "bit", "bar",  # 176-183
    "rac", "par", "lod", "dos", "bor", "toc", "hil", "mac",  # 184-191
    "tom", "dig", "fil", "fas", "mit", "hob", "har", "mig",  # 192-199
    "hin", "rad", "mas", "hal", "rag", "lag", "fad", "top",  # 200-207
    "mop", "hab", "nil", "nos", "mil", "fop", "fam", "dat",  # 208-215
    "nol", "din", "hat", "nac", "ris", "fot", "rib", "hoc",  # 216-223
    "nim", "lar", "fit", "wal", "rap", "sar", "nal", "mos",  # 224-231
    "lan", "don", "dan", "lad", "dov", "riv", "bac", "pol",  # 232-239
    "lap", "tal", "pit", "nam", "bon", "ros", "ton", "fod",  # 240-247
    "pon", "sov", "noc", "sor", "lav", "mat", "mip", "fip",  # 248-255
]
SUFFIXES = [
    "zod", "nec", "bud", "wes", "sev", "per", "sut", "let",  # 0-7
    "ful", "pen", "syt", "dur", "wep", "ser", "wyl", "sun",  # 8-15
    "ryp", "syx", "dyr", "nup", "heb", "peg", "lup", "dep",  # 16-23
    "dys", "put", "lug", "hec", "ryt", "tyv", "syd", "nex",  # 24-31
    "lun", "mep", "lut", "sep", "pes", "del", "sul", "ped",  # 32-39
    "tem", "led", "tul", "met", "wen", "byn", "hex", "feb",  # 40-47
    "pyl", "dul", "het", "mev", "rut", "tyl", "wyd", "tep",  # 48-55
    "bes", "dex", "sef", "wyc", "bur", "der", "nep", "pur",  # 56-63
    "rys", "reb", "den", "nut", "sub", "pet", "rul", "syn",  # 64-71
    "reg", "tyd", "sup", "sem", "wyn", "rec", "meg", "net",  # 72-79
    "sec", "mul", "nym", "tev", "web", "sum", "mut", "nyx",  # 80-87
    "rex", "teb", "fus", "hep", "ben", "mus", "wyx", "sym",  # 88-95
    "sel", "ruc", "dec", "wex", "syr", "wet", "dyl", "myn",  # 96-103
    "mes", "det", "bet", "bel", "tux", "tug", "myr", "pel",  # 104-111
    "syp", "ter", "meb", "set", "dut", "deg", "tex", "sur",  # 112-119
    "fel", "tud", "nux", "rux", "ren", "wyt", "nub", "med",  # 120-127
    "lyt", "dus", "neb", "rum", "tyn", "seg", "lyx", "pun",  # 128-135
    "res", "red", "fun", "rev", "ref", "mec", "ted", "rus",  # 136-143
    "bex", "leb", "dux", "ryn", "num", "pyx", "ryg", "ryx",  # 144-151
    "fep", "tyr", "tus", "tyc", "leg", "nem", "fer", "mer",  # 152-159
    "ten", "lus", "nus", "syl", "tec", "mex", "pub", "rym",  # 160-167
    "tuc", "fyl", "lep", "deb", "ber", "mug", "hut", "tun",  # 168-175
    "byl", "sud", "pem", "dev", "lur", "def", "bus", "bep",  # 176-183
    "run", "mel", "pex", "dyt", "byt", "typ", "lev", "myl",  # 184-191
    "wed", "duc", "fur", "fex", "nul", "luc", "len", "ner",  # 192-199
    "lex", "rup", "ned", "lec", "ryd", "lyd", "fen", "wel",  # 200-207
    "nyd", "hus", "rel", "rud", "nes", "hes", "fet", "des",  # 208-215
    "ret", "dun", "ler", "nyr", "seb", "hul", "ryl", "lud",  # 216-223
    "rem", "lys", "fyn", "wer", "ryc", "sug", "nys", "nyl",  # 224-231
    "lyn", "dyn", "dem", "lux", "fed", "sed", "bec", "mun",  # 232-239
    "lyr", "tes", "mud", "nyt", "byr", "sen", "weg", "fyr",  # 240-247
    "mur", "tel", "rep", "teg", "pec", "nel", "nev", "fes",  # 248-255
]
