name: Deploy to distribution ship
on:
  push:
    branches:
      - main

env:
  TMUX_TAB:  sponsor
  DESK:      groundwire
  SHIP_HOST: root@143.198.70.9
  DIST_PIER: watwyd-bannyt-parmep-sivpes--motweb-dovfet-nilrec-daplyd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set PIER_PATH
        run: echo "PIER_PATH=/root/.local/share/groundwire-alpha/${DIST_PIER}" >> "$GITHUB_ENV"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build desks
        run: |
          make spv
          make groundwire

      - name: Create desk.ship
        run: |
          printf '%s\n' "~${DIST_PIER}" > dist-groundwire/desk.ship
          printf '%s\n' "~${DIST_PIER}" > dist-spv/desk.ship

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 143.198.70.9 >> ~/.ssh/known_hosts

      - name: Deploy Groundwire
        run: scp -r dist-groundwire/* ${SHIP_HOST}:${PIER_PATH}/groundwire/

      - name: Deploy Wallet
        run: scp -r dist-spv/* ${SHIP_HOST}:${PIER_PATH}/spv-wallet/

      - name: Commit desk on ship
        run: |
          ssh ${SHIP_HOST} "tmux send-keys -t ${TMUX_TAB} '|commit %groundwire' Enter"
          ssh ${SHIP_HOST} "tmux send-keys -t ${TMUX_TAB} '|commit %spv-wallet' Enter"
