// Hoon-DERIVED golden vectors for the full on-chain sotx encoding (with the
// [sig ship] header), generated with `urbit eval` of `p:(fax:plot ...)` against
// the exact +full/+skim plot structure in lib/urb-encoder.hoon. Unlike
// fixtures/encoder-vectors.json (generated by the Python port), these are
// independent of Causeway's own encoders — so they catch divergences the
// Python-derived fixtures enshrined (notably the inverted %keys breach bit).

import { describe, expect, test } from "vitest";
import { encodeFull } from "../src/protocol/encoder.js";
import { bytesToAtomLE } from "../src/protocol/bitwriter.js";
import type { SkimSotx } from "../src/protocol/types.js";

const ux = (s: string): bigint => BigInt("0x" + s.replace(/\./g, ""));

// ship = 0x42cd (~daplyd), sig = ~ (none) for all vectors.
function full(skim: SkimSotx): bigint {
  return bytesToAtomLE(encodeFull([{ ship: 0x42cdn, sig: null, skim }]));
}

describe("full sotx encoding vs Hoon fax:plot", () => {
  test("%keys, no breach — breach loobean %.n encodes bit 1", () => {
    // p:(fax:plot [0 [s+~ 0 [2 0] ~] [128 0x42cd] [s+~ 0 [7 2] [1 %.n] (mat 0xdead.beef) ~] ~])
    expect(full({ op: "keys", pass: 0xdeadbeefn, breach: false })).toBe(
      ux("37.ab6f.bbc1.0208.0000.0000.0000.0000.0000.0000.0001.0b34"),
    );
  });

  test("%keys, breach — breach loobean %.y encodes bit 0", () => {
    // Same, with [1 %.y]; differs from the above by exactly the breach bit.
    expect(full({ op: "keys", pass: 0xdeadbeefn, breach: true })).toBe(
      ux("37.ab6f.bbc1.0008.0000.0000.0000.0000.0000.0000.0001.0b34"),
    );
  });

  test("%spawn — header + pass + no-fief + to{spkh,off0,tej0,vout0}", () => {
    // p:(fax:plot [0 [s+~ 0 [2 0] ~] [128 0x42cd]
    //   [s+~ 0 [7 1] [1 0] (mat 0xc0.ffee) [s+~ 0 [2 0] ~]
    //     [s+~ 0 [256 0x11.2233] (mat 0) (mat 0) [2 1] (mat 0) ~] ~] ~])
    const spkh = new Uint8Array(32);
    spkh[0] = 0x33; spkh[1] = 0x22; spkh[2] = 0x11; // LE bytes of 0x112233
    expect(full({
      op: "spawn",
      pass: 0xc0ffeen,
      fief: null,
      to: { spkh, off: 0n, tej: 0n, vout: 0n },
    })).toBe(ux(
      "5.c000.0000.0000.0000.0000.0000.0000.0000.0000.0000.0000" +
      ".0000.0000.0000.0004.488c.cc0f.fee8.8004.0000.0000.0000" +
      ".0000.0000.0000.0001.0b34",
    ));
  });
});
