// Cross-checks the TS mnemonym port against golden vectors generated by the
// gwbtc/mnemonyms reference (its shared test-vectors for generic entropy, plus
// tweaked 128-bit comet-@p vectors incl. edge cases). Fixture:
// tests/fixtures/mnemonyms.json.

import { describe, expect, test } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  bytesToMnemonym, mnemonymToBytes, atomToMnemonym, mnemonymToAtom,
  abridgeMnemonym, foreshortenMnemonym, validateMnemonym, isMnemonym, displayId,
} from "../src/protocol/mnemonym.js";
import { atomToPatp } from "../src/protocol/patp.js";

type Golden = {
  generic: Array<{ hex: string; strength: number; nym: string }>;
  comet: Array<{ atom: string; nym: string; abridge: string; foreshorten: string }>;
};
const golden: Golden = JSON.parse(
  readFileSync(resolve(__dirname, "fixtures/mnemonyms.json"), "utf8"),
);

function hexToBytes(h: string): Uint8Array {
  const out = new Uint8Array(h.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(h.slice(i * 2, i * 2 + 2), 16);
  return out;
}
function bytesToHex(b: Uint8Array): string {
  return Array.from(b, (x) => x.toString(16).padStart(2, "0")).join("");
}

describe("mnemonym vs gwbtc reference", () => {
  test("generic entropy vectors (untweaked) round-trip", () => {
    for (const v of golden.generic) {
      const data = hexToBytes(v.hex);
      const opts = { tweaked: false, strength: v.strength };
      expect(bytesToMnemonym(data, opts)).toBe(v.nym);
      expect(bytesToHex(mnemonymToBytes(v.nym, opts))).toBe(v.hex);
    }
  });

  test("comet @p vectors (tweaked, 128-bit) round-trip", () => {
    for (const v of golden.comet) {
      const atom = BigInt(v.atom);
      expect(atomToMnemonym(atom)).toBe(v.nym);           // default tweaked+128
      expect(mnemonymToAtom(v.nym)).toBe(atom);
      expect(abridgeMnemonym(v.nym)).toBe(v.abridge);
      expect(foreshortenMnemonym(v.nym)).toBe(v.foreshorten);
    }
  });

  test("tweaked vs untweaked prefix", () => {
    const atom = BigInt("0xdeadbeefcafebabe1122334455667788");
    expect(atomToMnemonym(atom, { tweaked: true }).startsWith(".")).toBe(true);
    expect(atomToMnemonym(atom, { tweaked: true }).startsWith("..")).toBe(false);
    expect(atomToMnemonym(atom, { tweaked: false }).startsWith("..")).toBe(true);
  });

  test("validate + isMnemonym", () => {
    const good = golden.comet[0]!.nym;
    expect(validateMnemonym(good)).toBe(true);
    expect(isMnemonym(good)).toBe(true);
    // corrupt the last word → checksum mismatch
    expect(validateMnemonym(good.replace(/\.[a-z]+$/, ".aback"))).toBe(false);
    expect(isMnemonym("~sampel-palnet")).toBe(false);
    expect(validateMnemonym(".notarealword")).toBe(false);
  });

  test("displayId: comets render as mnemonyms, stars/galaxies as @p", () => {
    const comet = BigInt("0xe7f38742227bf54ec48be13dba9242cd");
    expect(displayId(comet)).toBe(atomToMnemonym(comet));
    expect(displayId(comet).startsWith(".")).toBe(true);
    // ~daplyd is a star (16-bit) — not a comet, so it stays a @p.
    expect(displayId(0x42cdn)).toBe(atomToPatp(0x42cdn));
    expect(displayId(0x42cdn)).toBe("~daplyd");
    // boundary: exactly 2^64 is the first comet.
    expect(displayId((1n << 64n) - 1n).startsWith("~")).toBe(true); // moon → @p
    expect(displayId(1n << 64n).startsWith(".")).toBe(true);        // comet → mnemonym
  });

  test("edge cases: zero and small atoms", () => {
    expect(atomToMnemonym(0n)).toBe(".abducts");     // all-zero entropy → 1 word
    expect(mnemonymToAtom(".abducts")).toBe(0n);
    expect(atomToMnemonym(0x42cdn)).toBe(".allied.inflict"); // ~daplyd star value
  });
});
